%% Copyright (c) 2026 Demet Yesilbas. GPL-3.0 (see the repository LICENSE).
% Part of the Galea VR driving-hazards study code (Cannard & Yesilbas 2026,
% osf.io/xuw34). Loads its inputs from data/galea_ML_dataset.mat.

%% =========================================================
% 02_EEG_PrePost_Permutation_N16.m
%
% Within-subject label permutation analysis
%
% N = 16 participants
% Conditions:
%   1 = crash
%   2 = no-crash
%
% Time windows:
%   POST:  0 to +1200 ms
%   PRE:  -1200 to 0 ms
%
% Validation:
%   Leave-One-Subject-Out cross-validation (LOSO)
%
% Permutation:
%   1000 within-subject label permutations
%
% Required input variables:
%   ERP_avg
%   ERP_times
%   subjects
%
% Required files:
%   N16_EEG_classification_results.mat
%
% Required functions:
%   runLOSOclassification.m
%   permutationLOSO.m
%% =========================================================

clc;
rng(42);

% ---- data (from data/galea_ML_dataset.mat) ----
D = load(fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'galea_ML_dataset.mat'), 'ERP_avg', 'ERP_times', 'subjects');
ERP_avg   = D.ERP_avg;
ERP_times = D.ERP_times;
subjects  = D.subjects;



%% =========================================================
% SETTINGS
%% =========================================================

crashCond   = 1;
noCrashCond = 2;

nPerm = 1000;


%% =========================================================
% REBUILD EEG DATASETS
%% =========================================================

subjects_str = string(subjects(:));

postIdx = ERP_times >= 0 & ERP_times <= 1200;
preIdx  = ERP_times >= -1200 & ERP_times < 0;

nSub = numel(subjects_str);

nPostFeatures = size(ERP_avg,3) * sum(postIdx);
nPreFeatures  = size(ERP_avg,3) * sum(preIdx);

X_EEG_POST = zeros(2*nSub,nPostFeatures);
X_EEG_PRE  = zeros(2*nSub,nPreFeatures);

Y16 = strings(2*nSub,1);
subjectID16 = strings(2*nSub,1);

row = 0;

for s = 1:nSub

    % -------------------------------------------------------
    % CRASH
    % -------------------------------------------------------

    row = row + 1;

    tempPost = squeeze(ERP_avg(s,crashCond,:,postIdx));
    tempPre  = squeeze(ERP_avg(s,crashCond,:,preIdx));

    X_EEG_POST(row,:) = tempPost(:)';
    X_EEG_PRE(row,:)  = tempPre(:)';

    Y16(row) = "crash";
    subjectID16(row) = subjects_str(s);


    % -------------------------------------------------------
    % NO-CRASH
    % -------------------------------------------------------

    row = row + 1;

    tempPost = squeeze(ERP_avg(s,noCrashCond,:,postIdx));
    tempPre  = squeeze(ERP_avg(s,noCrashCond,:,preIdx));

    X_EEG_POST(row,:) = tempPost(:)';
    X_EEG_PRE(row,:)  = tempPre(:)';

    Y16(row) = "nocrash";
    subjectID16(row) = subjects_str(s);

end

Y16 = categorical(Y16);

uniqueSubjects16 = unique(subjectID16,'stable');

cv16 = cvpartition(numel(uniqueSubjects16),'LeaveOut');


fprintf('\n========================================\n');
fprintf('PERMUTATION DATASETS\n');
fprintf('========================================\n');

fprintf('POST: %d observations x %d features\n', ...
    size(X_EEG_POST,1),size(X_EEG_POST,2));

fprintf('PRE : %d observations x %d features\n', ...
    size(X_EEG_PRE,1),size(X_EEG_PRE,2));


%% =========================================================
% LOAD OBSERVED LOSO RESULTS
%
% These results are generated by:
%   01_EEG_PrePost_LOSO_N16.m
%% =========================================================

load('N16_EEG_classification_results.mat', ...
    'POST_results','PRE_results');


%% =========================================================
% POST-STIMULUS PERMUTATION TEST
%% =========================================================

fprintf('\n========================================\n');
fprintf('POST EEG PERMUTATION TEST\n');
fprintf('========================================\n');

POST_permP = permutationLOSO( ...
    X_EEG_POST, ...
    [], ...
    Y16, ...
    subjectID16, ...
    uniqueSubjects16, ...
    cv16, ...
    "EEG", ...
    POST_results.Accuracy, ...
    nPerm);

POST_results.PermutationP = POST_permP;

disp(POST_results);


%% =========================================================
% PRE-STIMULUS PERMUTATION TEST
%% =========================================================

fprintf('\n========================================\n');
fprintf('PRE EEG PERMUTATION TEST\n');
fprintf('========================================\n');

PRE_permP = permutationLOSO( ...
    X_EEG_PRE, ...
    [], ...
    Y16, ...
    subjectID16, ...
    uniqueSubjects16, ...
    cv16, ...
    "EEG", ...
    PRE_results.Accuracy, ...
    nPerm);

PRE_results.PermutationP = PRE_permP;

disp(PRE_results);


%% =========================================================
% SAVE RESULTS
%% =========================================================

save('N16_EEG_permutation_results.mat', ...
    'POST_results', ...
    'PRE_results', ...
    'POST_permP', ...
    'PRE_permP');

writetable(POST_results, ...
    'Post1200_N16_LOSO_withPermutation.csv');

writetable(PRE_results, ...
    'Pre1200_N16_LOSO_withPermutation.csv');


fprintf('\n========================================\n');
fprintf('PERMUTATION ANALYSIS COMPLETE\n');
fprintf('========================================\n');